// <auto-generated />
using System;
using LetsHang.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LetsHang.Migrations.Event
{
    [DbContext(typeof(EventContext))]
    [Migration("20191217215556_ResetDb1")]
    partial class ResetDb1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LetsHang.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventLocation")
                        .HasColumnType("text");

                    b.Property<string>("EventTime")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            EventId = 1L,
                            CreatedAt = new DateTime(2019, 12, 17, 14, 55, 56, 519, DateTimeKind.Local).AddTicks(6750),
                            Creator = "Flachman03",
                            Description = "Drink our faces off.",
                            EventLocation = "The Pub on Penn",
                            EventTime = "Right Meow",
                            Title = "Hang at Pub"
                        },
                        new
                        {
                            EventId = 2L,
                            CreatedAt = new DateTime(2019, 12, 17, 14, 55, 56, 524, DateTimeKind.Local).AddTicks(9610),
                            Creator = "Garrett03",
                            Description = "Watch tv and chill",
                            EventLocation = "My House",
                            EventTime = "Later Tonight",
                            Title = "Hang out at Home"
                        },
                        new
                        {
                            EventId = 3L,
                            CreatedAt = new DateTime(2019, 12, 17, 14, 55, 56, 524, DateTimeKind.Local).AddTicks(9650),
                            Creator = "Jacqui03",
                            Description = "Home Alone and Home Alone 2!",
                            EventLocation = "Hollywood",
                            EventTime = "Tonight",
                            Title = "Watch christmas movies and get krunk"
                        });
                });

            modelBuilder.Entity("LetsHang.Models.Invited", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("FriendId")
                        .HasColumnType("bigint");

                    b.Property<int>("InviteStatus")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Invites");
                });
#pragma warning restore 612, 618
        }
    }
}
