// <auto-generated />
using LetsHang.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LetsHang.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20191217213655_resetSeed1")]
    partial class resetSeed1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LetsHang.Models.Friend", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FriendId")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Friend");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FriendId = 2L,
                            RequestStatus = 2,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            FriendId = 3L,
                            RequestStatus = 2,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            FriendId = 4L,
                            RequestStatus = 2,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            FriendId = 3L,
                            RequestStatus = 2,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            FriendId = 3L,
                            RequestStatus = 2,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            FriendId = 4L,
                            RequestStatus = 2,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("LetsHang.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            ApiKey = "A93reRTUJHsCuQSHRAL3GxqOJyDmQpCgps102ciuabcA",
                            Email = "user@email.com",
                            Name = "Ryan Flachman",
                            Password = "password",
                            PhoneNumber = "1111111111",
                            UserName = "Flachman03"
                        },
                        new
                        {
                            UserId = 2L,
                            ApiKey = "B93reRTUJHsCuQSHRCL3GxqOJyDmQpCgps102ciuabc",
                            Email = "user1@email.com",
                            Name = "Garrett Flachman",
                            Password = "password",
                            PhoneNumber = "2222222222",
                            UserName = "Garrett03"
                        },
                        new
                        {
                            UserId = 3L,
                            ApiKey = "C93reRTUJHsCuQSHRXL3GxqOJyDmQpCgps102ciuabc",
                            Email = "user2@email.com",
                            Name = "Jacqui Long",
                            Password = "password",
                            PhoneNumber = "3333333333",
                            UserName = "Jacqui03"
                        },
                        new
                        {
                            UserId = 4L,
                            ApiKey = "D93reRTUJHsCuQSHRXL3GxqOJyDmQpCgps102ciuabc",
                            Email = "user3@email.com",
                            Name = "Steve Rumizen",
                            Password = "password",
                            PhoneNumber = "5555555555",
                            UserName = "Steve03"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
